const Map<String, String> appStringsEn = {
  'appName': 'Motivation Quotes',
  'appTagline': 'Daily inspiration to fuel your journey',
  'splashLoading': 'Loading inspiration...',
  'onboardingTitle1': 'Quote every day',
  'onboardingDesc1': 'Start each morning with a powerful motivational quote tailored for today.',
  'onboardingTitle2': 'Save your favorites',
  'onboardingDesc2': 'Heart the quotes that move you. Build your personal collection of inspiration.',
  'onboardingTitle3': 'Earn stars & customize',
  'onboardingDesc3': 'Collect stars daily, buy packs via Google Play, unlock themes, skins and premium features.',
  'getStarted': 'Get Started',
  'skip': 'Skip',
  'next': 'Next',
  'navHome': 'Today',
  'navExplore': 'Explore',
  'navFavorites': 'Favorites',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'dailyQuote': 'Quote of the Day',
  'favorite': 'Favorite',
  'share': 'Share',
  'newQuote': 'Next',
  'favorites': 'Favorites',
  'explore': 'Explore',
  'noFavorites': 'No favorites yet',
  'noFavoritesHint': 'Tap the heart on any quote to save it here.',
  'favoriteLimitReached': 'Favorite limit reached — unlock unlimited in Shop',
  'favoriteLimitInfo': '{current}/{max} favorites (free plan)',
  'addedToFavorites': 'Added to favorites',
  'removedFromFavorites': 'Removed from favorites',
  'sharedVia': 'Motivation Quotes',
  'allCategories': 'All',
  'cat_success': 'Success',
  'cat_motivation': 'Motivation',
  'cat_perseverance': 'Perseverance',
  'cat_dreams': 'Dreams',
  'cat_courage': 'Courage',
  'cat_happiness': 'Happiness',
  'cat_wisdom': 'Wisdom',
  'cat_mindset': 'Mindset',
  'adPlaceholder': 'Ad space — Remove ads in Shop',
  'removeAds': 'Remove',
  'save': 'Save',
  'cancel': 'Cancel',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Earn stars or buy more to unlock',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Card skins',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items in this category',
  'yourWallet': 'Your star wallet',
  'coinsLabel': 'stars',
  'earnCoins': 'Earn stars free',
  'earnStepDaily': '• Daily login: +10 stars',
  'earnStepFavorite': 'Favorite quotes',
  'earnStepFavoriteDesc': '• Favorite: +5 stars (max 5/day)',
  'earnStepShare': 'Share quotes',
  'earnStepShareDesc': '• Share: +5 stars (max 3/day)',
  'earnStepBuy': '• Buy star packs via Google Play',
  'claimDailyButton': 'Claim daily +10',
  'dailyRewardDone': 'Daily reward claimed',
  'buyCoins': 'Buy stars',
  'buyCoinsDesc': 'Purchase star packs to unlock items faster.',
  'yourCoins': 'You have {count} stars',
  'coinPack': 'Pack {num}',
  'coinAmount': '{count} stars',
  'earnCoinsHint': 'Or earn stars for free in the wallet section above.',
  'billingDisabled': 'Google Billing disabled — redeem with stars only',
  'billingUnavailable': 'Google Play Billing is not available',
  'productsNotFound': 'Products not found. Check Play Console setup.',
  'processingPurchase': 'Processing purchase...',
  'openingBilling': 'Opening Google Play...',
  'configNetworkError': 'Network error. Using cached config.',
  'configTimeout': 'Request timed out. Using cached config.',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'owned': 'Owned',
  'apply': 'Apply',
  'applied': 'Applied!',
  'resetDefault': 'Default',
  'resetToDefault': 'Reset to default',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide banner ads permanently.',
  'removeAdsIap': 'Buy via Google Play',
  'removeAdsUnlocked': 'Ads removed!',
  'buyWithGooglePlay': 'Buy now',
  'shopThemeSunset': 'Sunset theme',
  'shopThemeSunsetDesc': 'Warm coral tones.',
  'shopThemeMidnight': 'Midnight theme',
  'shopThemeMidnightDesc': 'Deep blue night vibes.',
  'shopThemeTropical': 'Tropical theme',
  'shopThemeTropicalDesc': 'Fresh green mood.',
  'shopThemeSakura': 'Sakura theme',
  'shopThemeSakuraDesc': 'Soft pink blossom.',
  'shopBgSunrise': 'Sunrise glow',
  'shopBgSunriseDesc': 'Warm orange gradient.',
  'shopBgOcean': 'Ocean waves',
  'shopBgOceanDesc': 'Blue wave gradient.',
  'shopBgAurora': 'Aurora borealis',
  'shopBgAuroraDesc': 'Purple-green aurora.',
  'shopBgGalaxy': 'Galaxy night',
  'shopBgGalaxyDesc': 'Deep space gradient.',
  'shopSkinGlass': 'Glass card',
  'shopSkinGlassDesc': 'Frosted glass quote card.',
  'shopSkinMinimal': 'Minimal card',
  'shopSkinMinimalDesc': 'Clean sharp edges.',
  'shopSkinElegant': 'Elegant card',
  'shopSkinElegantDesc': 'Rounded premium style.',
  'shopFeatUnlimitedFav': 'Unlimited favorites',
  'shopFeatUnlimitedFavDesc': 'Save unlimited quotes (free: 15).',
  'shopFeatFonts': 'Premium fonts',
  'shopFeatFontsDesc': 'Unlock Playfair, Lora & Caveat fonts.',
  'shopFeatNotification': 'Daily reminder',
  'shopFeatNotificationDesc': 'Set custom notification time.',
  'shopFeatExport': 'Export favorites',
  'shopFeatExportDesc': 'Export favorites as JSON.',
  'shopFeatWidget': 'Widget styles',
  'shopFeatWidgetDesc': 'Premium home screen widget themes.',
  'shopFeatNoWatermark': 'No watermark',
  'shopFeatNoWatermarkDesc': 'Share quotes without app branding.',
  'coinsAdded': '+{amount} stars added to wallet!',
  'dailyRewardClaimed': '+{amount} stars — daily reward!',
  'favoriteRewardEarned': '+{amount} stars — favorite added!',
  'shareRewardEarned': '+{amount} stars — quote shared!',
  'coinRewardSub': 'Wallet balance: {balance} stars',
  'settingsTitle': 'Settings',
  'language': 'Language',
  'english': 'English',
  'vietnamese': 'Vietnamese',
  'darkMode': 'Dark mode',
  'privacyPolicy': 'Privacy policy',
  'version': 'Version',
  'about': 'About',
  'aboutDesc': 'Motivation Quotes delivers daily inspiration. All favorites are stored locally on your device.',
  'activeTheme': 'Active theme',
  'activeBackground': 'Active background',
  'activeSkin': 'Active card skin',
  'quoteFont': 'Quote font',
  'fontOutfit': 'Outfit (default)',
  'fontPlayfair': 'Playfair Display',
  'fontLora': 'Lora',
  'fontCaveat': 'Caveat',
  'fontsLocked': 'Unlock premium fonts in Shop',
  'notificationHour': 'Daily reminder hour',
  'notificationLocked': 'Unlock daily reminder in Shop',
  'widgetInfo': 'Home screen widget',
  'widgetInfoDesc': 'Long-press home screen → Widgets → Motivation Quotes',
  'widgetStylesLocked': 'Unlock widget styles in Shop',
  'appearance': 'Appearance',
  'other': 'Other',
  'exportSuccess': 'Favorites copied to clipboard',
  'openShop': 'Open Shop',
  'openShopDesc': 'Themes, features & buy stars',
  'copyright': '© 2026 Motivation Quotes',
  'activeCustomization': 'Customization',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody': 'Motivation Quotes stores favorites locally on your device. We do not collect or upload your personal data.\n\nInternet is used only to fetch IAP configuration (R211.json) and process Google Play purchases.\n\nPurchases are handled by Google Play Billing. We do not store payment card information.\n\nContact: support@motivationquotes.app',
};
