const Map<String, String> appStringsVi = {
  'appName': 'Motivation Quotes',
  'appTagline': 'Cảm hứng mỗi ngày cho hành trình của bạn',
  'splashLoading': 'Đang tải cảm hứng...',
  'onboardingTitle1': 'Quote mỗi ngày',
  'onboardingDesc1': 'Bắt đầu mỗi buổi sáng với câu quote động lực dành riêng cho hôm nay.',
  'onboardingTitle2': 'Lưu yêu thích',
  'onboardingDesc2': 'Lưu những câu quote chạm đến trái tim. Xây dựng bộ sưu tập cảm hứng riêng.',
  'onboardingTitle3': 'Kiếm sao & tùy chỉnh',
  'onboardingDesc3': 'Nhận sao mỗi ngày, mua gói qua Google Play, mở khóa theme, skin và tính năng premium.',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',
  'navHome': 'Hôm nay',
  'navExplore': 'Khám phá',
  'navFavorites': 'Yêu thích',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',
  'dailyQuote': 'Quote hôm nay',
  'favorite': 'Yêu thích',
  'share': 'Chia sẻ',
  'newQuote': 'Tiếp',
  'favorites': 'Yêu thích',
  'explore': 'Khám phá',
  'noFavorites': 'Chưa có yêu thích',
  'noFavoritesHint': 'Nhấn trái tim trên quote để lưu tại đây.',
  'favoriteLimitReached': 'Đã đạt giới hạn — mở khóa không giới hạn trong Cửa hàng',
  'favoriteLimitInfo': '{current}/{max} yêu thích (gói miễn phí)',
  'addedToFavorites': 'Đã thêm yêu thích',
  'removedFromFavorites': 'Đã xóa khỏi yêu thích',
  'sharedVia': 'Motivation Quotes',
  'allCategories': 'Tất cả',
  'cat_success': 'Thành công',
  'cat_motivation': 'Động lực',
  'cat_perseverance': 'Kiên trì',
  'cat_dreams': 'Ước mơ',
  'cat_courage': 'Dũng cảm',
  'cat_happiness': 'Hạnh phúc',
  'cat_wisdom': 'Trí tuệ',
  'cat_mindset': 'Tư duy',
  'adPlaceholder': 'Quảng cáo — Gỡ quảng cáo trong Cửa hàng',
  'removeAds': 'Gỡ QC',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Kiếm sao hoặc mua thêm để mở khóa',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Theme',
  'shopMenuCards': 'Hình nền',
  'shopMenuSkins': 'Skin thẻ',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Không có mục trong danh mục này',
  'yourWallet': 'Ví sao của bạn',
  'coinsLabel': 'sao',
  'earnCoins': 'Kiếm sao miễn phí',
  'earnStepDaily': '• Đăng nhập hàng ngày: +10 sao',
  'earnStepFavorite': 'Yêu thích quote',
  'earnStepFavoriteDesc': '• Yêu thích: +5 sao (tối đa 5/ngày)',
  'earnStepShare': 'Chia sẻ quote',
  'earnStepShareDesc': '• Chia sẻ: +5 sao (tối đa 3/ngày)',
  'earnStepBuy': '• Mua gói sao qua Google Play',
  'claimDailyButton': 'Nhận +10 hôm nay',
  'dailyRewardDone': 'Đã nhận thưởng hôm nay',
  'buyCoins': 'Mua sao',
  'buyCoinsDesc': 'Mua gói sao để mở khóa nhanh hơn.',
  'yourCoins': 'Bạn có {count} sao',
  'coinPack': 'Gói {num}',
  'coinAmount': '{count} sao',
  'earnCoinsHint': 'Hoặc kiếm sao miễn phí ở phần ví phía trên.',
  'billingDisabled': 'Google Billing tắt — chỉ đổi bằng sao',
  'billingUnavailable': 'Google Play Billing không khả dụng',
  'productsNotFound': 'Không tìm thấy sản phẩm. Kiểm tra Play Console.',
  'processingPurchase': 'Đang xử lý giao dịch...',
  'openingBilling': 'Đang mở Google Play...',
  'configNetworkError': 'Lỗi mạng. Dùng cấu hình đã lưu.',
  'configTimeout': 'Hết thời gian chờ. Dùng cấu hình đã lưu.',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'owned': 'Đã mua',
  'apply': 'Áp dụng',
  'applied': 'Đã áp dụng!',
  'resetDefault': 'Mặc định',
  'resetToDefault': 'Đã về mặc định',
  'shopRemoveAds': 'Gỡ quảng cáo',
  'shopRemoveAdsDesc': 'Ẩn banner quảng cáo vĩnh viễn.',
  'removeAdsIap': 'Mua qua Google Play',
  'removeAdsUnlocked': 'Đã gỡ quảng cáo!',
  'buyWithGooglePlay': 'Mua ngay',
  'shopThemeSunset': 'Theme hoàng hôn',
  'shopThemeSunsetDesc': 'Tông cam ấm áp.',
  'shopThemeMidnight': 'Theme đêm',
  'shopThemeMidnightDesc': 'Xanh đêm sâu lắng.',
  'shopThemeTropical': 'Theme nhiệt đới',
  'shopThemeTropicalDesc': 'Xanh tươi mát.',
  'shopThemeSakura': 'Theme sakura',
  'shopThemeSakuraDesc': 'Hồng hoa anh đào.',
  'shopBgSunrise': 'Bình minh',
  'shopBgSunriseDesc': 'Gradient cam ấm.',
  'shopBgOcean': 'Đại dương',
  'shopBgOceanDesc': 'Gradient sóng xanh.',
  'shopBgAurora': 'Cực quang',
  'shopBgAuroraDesc': 'Gradient tím-xanh.',
  'shopBgGalaxy': 'Galaxy',
  'shopBgGalaxyDesc': 'Gradient không gian.',
  'shopSkinGlass': 'Thẻ kính',
  'shopSkinGlassDesc': 'Thẻ quote hiệu ứng kính mờ.',
  'shopSkinMinimal': 'Thẻ tối giản',
  'shopSkinMinimalDesc': 'Góc vuông gọn gàng.',
  'shopSkinElegant': 'Thẻ sang trọng',
  'shopSkinElegantDesc': 'Bo tròn premium.',
  'shopFeatUnlimitedFav': 'Yêu thích không giới hạn',
  'shopFeatUnlimitedFavDesc': 'Lưu không giới hạn (miễn phí: 15).',
  'shopFeatFonts': 'Font premium',
  'shopFeatFontsDesc': 'Mở Playfair, Lora & Caveat.',
  'shopFeatNotification': 'Nhắc hàng ngày',
  'shopFeatNotificationDesc': 'Đặt giờ thông báo tùy chỉnh.',
  'shopFeatExport': 'Xuất yêu thích',
  'shopFeatExportDesc': 'Xuất yêu thích dạng JSON.',
  'shopFeatWidget': 'Style widget',
  'shopFeatWidgetDesc': 'Theme widget màn hình chính premium.',
  'shopFeatNoWatermark': 'Không watermark',
  'shopFeatNoWatermarkDesc': 'Chia sẻ không kèm tên app.',
  'coinsAdded': '+{amount} sao đã thêm vào ví!',
  'dailyRewardClaimed': '+{amount} sao — thưởng hàng ngày!',
  'favoriteRewardEarned': '+{amount} sao — đã yêu thích!',
  'shareRewardEarned': '+{amount} sao — đã chia sẻ!',
  'coinRewardSub': 'Số dư: {balance} sao',
  'settingsTitle': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'english': 'English',
  'vietnamese': 'Tiếng Việt',
  'darkMode': 'Chế độ tối',
  'privacyPolicy': 'Chính sách bảo mật',
  'version': 'Phiên bản',
  'about': 'Giới thiệu',
  'aboutDesc': 'Motivation Quotes mang cảm hứng mỗi ngày. Yêu thích được lưu cục bộ trên thiết bị.',
  'activeTheme': 'Theme đang dùng',
  'activeBackground': 'Hình nền đang dùng',
  'activeSkin': 'Skin thẻ đang dùng',
  'quoteFont': 'Font quote',
  'fontOutfit': 'Outfit (mặc định)',
  'fontPlayfair': 'Playfair Display',
  'fontLora': 'Lora',
  'fontCaveat': 'Caveat',
  'fontsLocked': 'Mở font premium trong Cửa hàng',
  'notificationHour': 'Giờ nhắc hàng ngày',
  'notificationLocked': 'Mở nhắc hàng ngày trong Cửa hàng',
  'widgetInfo': 'Widget màn hình',
  'widgetInfoDesc': 'Giữ màn hình chính → Widget → Motivation Quotes',
  'widgetStylesLocked': 'Mở style widget trong Cửa hàng',
  'appearance': 'Giao diện',
  'other': 'Khác',
  'exportSuccess': 'Đã sao chép yêu thích',
  'openShop': 'Mở Cửa hàng',
  'openShopDesc': 'Theme, tính năng & mua sao',
  'copyright': '© 2026 Motivation Quotes',
  'activeCustomization': 'Tùy chỉnh',
  'privacyPolicyTitle': 'Chính sách bảo mật',
  'privacyPolicyBody': 'Motivation Quotes lưu yêu thích cục bộ trên thiết bị. Chúng tôi không thu thập dữ liệu cá nhân.\n\nInternet chỉ dùng để lấy cấu hình IAP (R211.json) và xử lý mua hàng Google Play.\n\nGiao dịch qua Google Play Billing. Chúng tôi không lưu thông tin thẻ.\n\nLiên hệ: support@motivationquotes.app',
};
